services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    security_opt:
      - no-new-privileges:true
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"   # HTTP Web UI
      - "9443:9443"   # HTTPS Web UI (Optional, recommended)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data
    restart: unless-stopped
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges:true
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080:8080 # qBittorrent Web UI
      - 6881:6881 # qBittorrent TCP
      - 6881:6881/udp # qBittorrent UDP
      - 8989:8989 # Sonarr
      - 7878:7878 # Radarr
      - 8686:8686 # Lidarr
      - 9696:9696 # Prowlarr
      - 8191:8191 # Flaresolverr
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${MULLVAD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${MULLVAD_ADDRESS}
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24
      - DNS_UPDATE_PERIOD=0
      - DNS_ADDRESS=1.1.1.1
    restart: always

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - FOWNER
    environment:
      - PUID=1800
      - PGID=1800
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent/appdata:/config
      - ${ROOT_DIR}/downloads:/downloads
      - ${ROOT_DIR}/media:/media
    depends_on:
      gluetun:
        condition: service_healthy
    restart: always

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    network_mode: "service:gluetun"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - FOWNER
    environment:
      - PUID=1800
      - PGID=1800
      - TZ=Etc/UTC
    volumes:
      - ./lidarr/config:/config
      - ${ROOT_DIR}/media/music:/music 
      - ${ROOT_DIR}/downloads:/downloads
    depends_on:
      gluetun:
        condition: service_healthy
    restart: always

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:gluetun"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - FOWNER
    environment:
      - PUID=1800
      - PGID=1800
      - TZ=Etc/UTC
    volumes:
      - ./sonarr/data:/config
      - ${ROOT_DIR}/media/shows:/shows
      - ${ROOT_DIR}/downloads:/downloads
    depends_on:
      gluetun:
        condition: service_healthy
    restart: always

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: "service:gluetun"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - FOWNER
    environment:
      - PUID=1800
      - PGID=1800
      - TZ=Etc/UTC
    volumes:
      - ./radarr/data:/config 
      - ${ROOT_DIR}/media/movies:/movies
      - ${ROOT_DIR}/downloads:/downloads
    depends_on:
      gluetun:
        condition: service_healthy
    restart: always

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "service:gluetun" # Recommended to avoid ISP blocking indexers
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - FOWNER
    environment:
      - PUID=1800
      - PGID=1800
      - TZ=Etc/UTC
    volumes:
      - ./prowlarr/data:/config
      - ./scripts:/scripts
    depends_on:
      gluetun:
        condition: service_healthy
    restart: always

  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: "service:gluetun"
    security_opt:
      - no-new-privileges:true
    environment:
      - LOG_LEVEL=info
      - TZ=Etc/UTC
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1800:1800
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - FOWNER
    ports:
      - '8096:8096'
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - type: bind
        source: ${ROOT_DIR}/media
        target: /media
    restart: unless-stopped

  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp=unconfined
    environment:
      - PUID=1800
      - PGID=1800
      - TZ=Etc/UTC
    volumes:
      - ./calibre/config:/config
      - ${ROOT_DIR}/media/books:/books
    ports:
      - 8082:8080 # GUI
      - 8181:8181 # Server
      - 8084:8081 # OPDS
    shm_size: "1gb"
    restart: unless-stopped

  komga:
    image: gotson/komga:latest
    container_name: komga
    user: "1800:1800"
    environment:
      - TZ=America/New_York
      - JAVA_OPTS=-Xmx1g 
    volumes:
      - ./komga/config:/config
      - ${ROOT_DIR}/media/comics:/comics
      - ${ROOT_DIR}/media/manga:/manga
    ports:
      - 25600:25600
    restart: unless-stopped

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - FOWNER
    ports:
      - "13378:80"
    volumes:
      - ./audiobookshelf/config:/config
      - ./audiobookshelf/metadata:/metadata
      - ${ROOT_DIR}/media/audiobooks:/audiobooks
    environment:
      - TZ=America/Chicago
    restart: unless-stopped

  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    hostname: homeserver
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - FOWNER
      - SETGID
      - SETUID
    environment:
      - PUID=1000 
      - PGID=1000
    volumes:
      # Syncthing configuration & database
      - ./syncthing-data:/var/syncthing
      
      # Mapped targets on /data
      - /data/media/photos:/sync/photos
    ports:
      - "8384:8384"         # Web UI
      - "22000:22000/tcp"   # Sync Transfer TCP
      - "22000:22000/udp"   # Sync Transfer UDP
      - "21027:21027/udp"   # Local Discovery
    restart: unless-stopped
