# vim:ft=kitty

## name:     Catppuccin-Mocha
## author:   Pocco81 (https://github.com/Pocco81)
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/mocha.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #A7D4E1
background              #051F30
selection_foreground    #051F30
selection_background    #496E99

# Cursor colors
cursor                  #496E99
cursor_text_color       #496E99

# URL underline color when hovering with mouse
url_color               #496E99

# Kitty window border colors
active_border_color     #496E99
inactive_border_color   #496E99
bell_border_color       #496E99

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #496E99
active_tab_background   #496E99
inactive_tab_foreground #496E99
inactive_tab_background #496E99
tab_bar_background      #496E99

# Colors for marks (marked text in the terminal)
mark1_foreground #A7D4E1
mark1_background #496E99
mark2_foreground #A7D4E1
mark2_background #496E99
mark3_foreground #A7D4E1
mark3_background #496E99

# The 16 terminal colors

# black
color0 #496E99
color8 #496E99

# red
color1 #A7D4E1
color9 #A7D4E1

# green
color2  #A7D4E1
color10 #A7D4E1

# yellow
color3  #496E99
color11 #496E99

# blue
color4  #496E99
color12 #496E99

# magenta
color5  #496E99
color13 #496E99

# cyan
color6  #496E99
color14 #496E99

# white
color7  #496E99
color15 #496E99
