# vim:ft=kitty

## name:     Catppuccin-Mocha
## author:   Pocco81 (https://github.com/Pocco81)
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/mocha.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #D1E0EB
background              #1B1C16
selection_foreground    #1B1C16
selection_background    #B5CBDB

# Cursor colors
cursor                  #B5CBDB
cursor_text_color       #B5CBDB

# URL underline color when hovering with mouse
url_color               #B5CBDB

# Kitty window border colors
active_border_color     #B5CBDB
inactive_border_color   #B5CBDB
bell_border_color       #B5CBDB

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #B5CBDB
active_tab_background   #B5CBDB
inactive_tab_foreground #B5CBDB
inactive_tab_background #B5CBDB
tab_bar_background      #B5CBDB

# Colors for marks (marked text in the terminal)
mark1_foreground #D1E0EB
mark1_background #B5CBDB
mark2_foreground #D1E0EB
mark2_background #B5CBDB
mark3_foreground #D1E0EB
mark3_background #B5CBDB

# The 16 terminal colors

# black
color0 #B5CBDB
color8 #B5CBDB

# red
color1 #D1E0EB
color9 #D1E0EB

# green
color2  #D1E0EB
color10 #D1E0EB

# yellow
color3  #B5CBDB
color11 #B5CBDB

# blue
color4  #B5CBDB
color12 #B5CBDB

# magenta
color5  #B5CBDB
color13 #B5CBDB

# cyan
color6  #B5CBDB
color14 #B5CBDB

# white
color7  #B5CBDB
color15 #B5CBDB
