# vim:ft=kitty

## name:     Catppuccin-Mocha
## author:   Pocco81 (https://github.com/Pocco81)
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/mocha.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #ECC8A8
background              #210D0D
selection_foreground    #210D0D
selection_background    #D16754

# Cursor colors
cursor                  #D16754
cursor_text_color       #D16754

# URL underline color when hovering with mouse
url_color               #D16754

# Kitty window border colors
active_border_color     #D16754
inactive_border_color   #D16754
bell_border_color       #D16754

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #D16754
active_tab_background   #D16754
inactive_tab_foreground #D16754
inactive_tab_background #D16754
tab_bar_background      #D16754

# Colors for marks (marked text in the terminal)
mark1_foreground #ECC8A8
mark1_background #D16754
mark2_foreground #ECC8A8
mark2_background #D16754
mark3_foreground #ECC8A8
mark3_background #D16754

# The 16 terminal colors

# black
color0 #D16754
color8 #D16754

# red
color1 #ECC8A8
color9 #ECC8A8

# green
color2  #ECC8A8
color10 #ECC8A8

# yellow
color3  #D16754
color11 #D16754

# blue
color4  #D16754
color12 #D16754

# magenta
color5  #D16754
color13 #D16754

# cyan
color6  #D16754
color14 #D16754

# white
color7  #D16754
color15 #D16754
